---
title: " La reproductibilité scientifique: une arme précieuse contre la desinformation " 

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Pénélope Robert
    affiliation: "a"

address:
  - code: "a"
    address: "Université de Sherbrooke, Départment de biologie, 2500 Boulevard de l'Université, Sherbrooke, Québec, G1V 0A9"


abstract: |
  En réponse à l'article "Des études trop rapides en temps de COVID?" de l'Agence Science Presse, l'éditorial vous propose des piste de réflexion en reliant la crise de reproductibilité, la crise sanitaire ainsi que la crise climatique. La thèse défendue est que les facteurs qui limitent la reproductibilité scientique contribu à la désinformation et les fausses nouvelles ("fake news"). L'auteur discutent également des enjeux qui entravent la reproductivité tel que les conflits d'intérêt pouvant être relié à de la fraud ainsi que les solutions possibles comme l'accessibilité des données. 



## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle

bibliography: pnas-sample.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

output: rticles::pnas_article
---

Malgré toutes les terribles conséquences de la COVID-19, la pandémie a tout de même mis en lumière plusieurs réalités. Elle nous a montré qu'il y a effectivement une crise de reproductibilité dans le domaine scientifique qu'il est possible d'accélérer les délais de publication et donc de découvertes pour ainsi agir rapidement sur des fondements scientifiques. En effet, les serveurs de prépublication ont comme avantage de réduire les délais de publication. Par contre, il y a un revers de la médaille à cette rapidité et à son accessibilité @radiocan: la fiabilité des études est questionnable, car ce sont des recherches qui n'ont pas été révisées. En théorie, cette rapidité et accessibilité est très utile puisqu'elles permettent d'augmenter la révision par les pairs et donc la rapidité du processus. Le problème rencontré durant la pandémie est que les journalistes non aguerri et mal informé ont tiré avantage de ces plateformes et ont publié des études non validées @radiocan. C'est justement une autre leçon que la pandémie nous a révélée, les journalistes et éditeurs se doivent d'être plus rigoureux. Cela dit, c'est exactement de cette façon-là que la crédibilité scientifique prend un coup et laisse place à une panoplie de fausses études et à la désinformation. Le seul outil que nous avons pour réacquérir notre crédibilité est la reproductibilité. 

# Facteurs qui limitent la reproductibilité #

Lors un sondage émis par le journal *Nature* sur la reproductibilité les répondants ont mis en lumière les grandes lignes du problème. Les scientifiques relatent que dans les 3 grands facteurs qui affectent le plus la reproductibilité sont la sélectivité de l'information, la pression de publier ainsi que le peu de puissance statistique @Baker2016. Les deux premiers plus grands facteurs sont interreliés puisque c'est la pression de publier qui pousse des chercheurs à consciemment rapporter partiellement des informations ou des données afin de faire parler les résultats comme ils le veulent.
D'autres facteurs peuvent également être le manque de mentorat, une mauvaise méthode expérimentale et la fraude (qui selon moi est très proche de la sélectivité de l'information) @Baker2016.

# Conflits d'intérêts et fraude scientifique

Le même sondage du journal *Nature* a demandé quelles approches devraient être améliorées. De meilleures analyses statistiques, de meilleures méthodes et davantage de mentorat sont les répondes les plus populaires. C'est vrai, mais il n'y a pas de pistes de solution pour le plus gros problème: la pression de découvrir ce qu'on recherche et la pression de publication. Selon moi, la partie prenante la plus importante qui contribue à ce fléau est les sociétés de financement. Évidemment, c'est très dispendieux une recherche. Le problème est que les sociétés de financement, autant publiques que privées, fournissent de l'argent aux études qui ont le potentiel "prouver" ce qui les avantages. Il y a ici un gros conflit d'intérêts dans le processus. Ironiquement, les études qui semblent être le moins reproductibles ont moins de chance d'être publiées dans de grands journaux prestigieux. Évidemment, les sociétés de financement publique joue un rôle de bon samaritain puissent qu'elles poussent, théoriquement, pour le bien commun. Les compagnies privées par contre peuvent en faire à leur tête. Le meilleur exemple est celui de la crise climatique et de la compagnie pétrolière Exxon. Depuis au moins 1977 qu'Exxon sait scientifiquement que le CO2 produit par la combustion du pétrole contribuent au réchauffement climatique @exxon. C'est 11 ans avant même que la NASA lance l'alerte. Exxon a nié que leur conclusion n'était pas fiable. Depuis, ils sont devenus des leaders dans la désinformation scientifique autour de la crise climatique. C'est l'enquête sur Exxon par InsideClimate News qui a mis au grand jour des dizaines et des dizaines de documents qui relataient leur plan d'action. La citation suivante a été trouvée (traduit de l'anglais) : "La victoire sera atteinte lorsque le citoyen moyen sera incertain des changements climatiques" @exxon. Selon Greenpeace, Exxon a financiers pour plus de 30 millions de dollars US sur des recherches et des campagnes de publicité climatosceptiques @exxon. Le lobbying du pétrole est un très bel exemple de fraude scientifique qui perdure encore aujourd'hui.

# L'accessibilité à l'information brute #

Une des façons d'éviter le fiasco d'Exxon et d'avoir des études fiables c'est l'accessibilité des données. C'est un aspect fondamental et indispensable à la reproductibilité qu'il ne faut pas sous-estimée. C'est une action simple et facile puisque la technologie nous le permet @Poisot2013. Cette mesure permet également l'avancement de la science, sans avoir besoin d'un gros budget. Effectivement, cela permet que d'autres scientifiques utilisent les données soit pour répliquer l'expérience avec d'autres analyses ou soit pour effectuer une méta-analyse @mesirov. Dans le même ordre d'idée, de nombreuses collaborations peuvent naitre de ce partage d'informations et de piste de réflexion @Poisot2013.


# De l'urgence sanitaire à l'urgence climatique #

Nous avons donc vu jusqu'à présent qu'il est possible de faire accélérer la science et être reproductibilité du même coup. L'accessibilité des données et les serveurs de prépublication en sont des exemples. Maintenant que nous savons que c'est possible : pourquoi n'agissons-nous toujours pas sur la crise climatique? Pourquoi n'accélérons pas les données et les études sur le sujet afin d'enterrer "l'incertitude du citoyen moyen"? L'urgence climatique n'est-elle pas aussi si ce n'est pas plus importante que l'urgence sanitaire? Sans surprise, c'est une question d'argent. Le Canada a subventionné pour près de 330 millions de dollars pour la recherche sur la COVID-19 @covidcash. En 2019, c'est 175 millions de dollars qui sont débloqués pour la conservation @ecocash. Rien du tout depuis, mais le Ministre de l'Environnement, M. Guilbeault, accepte le projet d'extraction pétrolier de la Bay du Nord deux jours après le rapport exubérant du GIEC. Utilisons donc notre arme la plus précieuse, la reproductibilité scientifique, afin de remettre les pendules à l'heure et éviter d'autres catastrophes planétaires.



\pnasbreak
